language: cpp
compiler: gcc

addons: 
  # Boost
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # gcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo pip install codecov
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # OCLint
  - ./install_oclint.sh
  # GraphViz
  - sudo apt-get install -qq graphviz
  - # PDF
  - sudo apt-get install -qq babel
  - sudo apt-get install -qq lyx
  - sudo apt-get install -qq texlive # For pdflatex
  - sudo apt-get install -qq texlive-* # For pdflatex
  # Get my folder
  - my_github=${PWD##*/}  
  # boost_graph_cookbook_1, develop
  - cd ..; git clone https://github.com/richelbilderbeek/boost_graph_cookbook_1.git; cd boost_graph_cookbook_1; git checkout -t origin/develop; cd ..; cd $my_github

script: 
  - type dot
  # No GraphViz, test
  - qmake boost_graph_cookbook_2/boost_graph_cookbook_2_test_no_graphviz.pro
  - make debug
  - ./boost_graph_cookbook_2_test_no_graphviz
  # No Graphviz, normal
  #- qmake boost_graph_cookbook_2/boost_graph_cookbook_2_no_graphviz.pro
  #- make debug
  #- ./boost_graph_cookbook_2_no_graphviz
  # Graphviz, test
  - qmake boost_graph_cookbook_2/boost_graph_cookbook_2_test.pro
  - make debug
  - ./boost_graph_cookbook_2_test
  # Graphviz, normal
  #- qmake boost_graph_cookbook_2/boost_graph_cookbook_2.pro
  #- make debug
  #- ./boost_graph_cookbook_2
  # Prepare to get code coverag
  - cp debug/*.gcda boost_graph_cookbook_2 # Will this work?
  - cp debug/*.gcno boost_graph_cookbook_2 # Will this work?
  - cp debug/*.o boost_graph_cookbook_2 # Will this work?
  - cp debug/*.gcda . # Will this work?
  - cp debug/*.gcno . # Will this work?
  - cp debug/*.o . # Will this work?
  # Get code coverage
  - ./get_code_cov
  - codecov
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint, takes to long...
  # - travis_wait 60 ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - pdflatex -v
  - cd ~; find . | egrep "\.tex"
  - cd ~; find . | egrep "\.log"
  - cd /usr; find . | egrep "/texlive$"
  - cd /opt; find . | egrep "/texlive$"
  - cd /; find . | egrep "/texlive$"
  #- which tlmgr
  - echo $PATH
  - cat /home/travis/build/richelbilderbeek/boost_graph_cookbook_2/boost_graph_cookbook_2/boost_graph_cookbook_2.tex

