include(boost_graph_cookbook_2_no_graphviz_bundled_edges_and_vertices.pri)
include(boost_graph_cookbook_2_no_graphviz_bundled_vertices.pri)
include(boost_graph_cookbook_2_no_graphviz_no_properties.pri)
