INCLUDEPATH += $$PWD

include(boost_graph_cookbook_2_graphviz_only_bundled_edges_and_vertices.pri)
include(boost_graph_cookbook_2_graphviz_only_bundled_vertices.pri)
include(boost_graph_cookbook_2_graphviz_only_no_properties.pri)


