include(any_normal.pri)

# Equivalent to:
# include(boost_graph_cookbook_2.pri)

include(boost_graph_cookbook_2_bundled_edges_and_vertices.pri)
include(boost_graph_cookbook_2_bundled_vertices.pri)
include(boost_graph_cookbook_2_custom_and_selectable_edges_and_vertices.pri)
include(boost_graph_cookbook_2_custom_and_selectable_vertices.pri)
include(boost_graph_cookbook_2_custom_edges_and_vertices.pri)
include(boost_graph_cookbook_2_custom_vertices.pri)
include(boost_graph_cookbook_2_helper.pri)
include(boost_graph_cookbook_2_misc.pri)
include(boost_graph_cookbook_2_named_and_selectable_vertices.pri)
include(boost_graph_cookbook_2_named_edges_and_vertices.pri)
include(boost_graph_cookbook_2_named_graph.pri)
include(boost_graph_cookbook_2_named_vertices.pri)
include(boost_graph_cookbook_2_no_properties.pri)
include(boost_graph_cookbook_2_tutorial.pri)

SOURCES += main.cpp

# USe Graphviz
LIBS += -lboost_graph
